FROM docker.repository.cloudera.com/cdsw/engine:4

#tools required for building things
RUN apt-get  update && \
    apt-get install -y -q git maven
#TODO : move bigdl to the template 
RUN cd /tmp &&\
    git clone https://github.com/intel-analytics/BigDL.git
#Python packages ,try to  install but don't upgrade or remove packages already installed in base image.
COPY conda_requirements.txt /tmp/requirements.txt
RUN conda install --file /tmp/requirements.txt
